[tools]
python = "3.12"
uv = "latest"

[tasks.version]
run = """
echo "$(date +%Y%m%d%H%M%S)-$(git describe --always --dirty --exclude '*')"
"""

[tasks.docker]
run = "docker buildx build ."

[tasks.ci]
depends = ["test", "lint", "fmt-check"]
