apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "nais-verification.fullname" . }}-deploy-key
  labels:
    {{- include "nais-verification.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  suspend: true  # Suspended until needed APIs are in place
  template:
    metadata:
      labels:
        {{- include "nais-verification.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
      - command:
        - "/app/venv/bin/nais-verification"
        - "create-deploy-key"
        envFrom:
        - secretRef:
            name: {{ include "nais-verification.fullname" . }}
        env:
          - name: SECRET_NAME
            value: "{{ .Values.secretName }}"
          - name: SECRET_NAMESPACE
            value: "{{ .Release.Namespace }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1069
          runAsNonRoot: true
          runAsUser: 1069
        volumeMounts:
        - mountPath: /tmp
          name: writable-tmp
      securityContext: {}
      serviceAccountName: {{ include "nais-verification.serviceAccountName" . }}
      volumes:
      - emptyDir:
          medium: "Memory"
        name: writable-tmp
