apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "nais-verification.fullname" . }}-team
  labels:
    {{- include "nais-verification.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    {{- include "nais-verification.job-template" (set . "command" "create-team") | nindent 4 }}
