apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nais-verification.fullname" . }}
  labels:
    {{- include "nais-verification.labels" . | nindent 4 }}
stringData:
  NAIS_TEAMS_API_URL: "{{ .Values.naisTeams.apiUrl }}"
  NAIS_TEAMS_API_TOKEN: "{{ .Values.naisTeams.apiToken }}"
