apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nais-verification.fullname" . }}
  labels:
    {{- include "nais-verification.labels" . | nindent 4 }}
stringData:
  CONSOLE_API_URL: "{{ .Values.console.api_url }}"
  CONSOLE_API_TOKEN: "{{ .Values.console.api_token }}"
