---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nais-verification.serviceAccountName" . }}
  labels:
    {{- include "nais-verification.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nais-verification.fullname" . }}
  labels:
    {{- include "nais-verification.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - {{ .Values.secretName }}
    verbs:
      - get
      - list
      - create
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nais-verification.fullname" . }}
  labels:
    {{- include "nais-verification.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nais-verification.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nais-verification.serviceAccountName" . }}
    namespace: "{{ .Release.Namespace }}"
