dependencies:
  - allOf:
      - nais-api
      - hookd
environmentKinds:
  - management
values:
  naisTeams.apiToken:
    computed:
      template: '"{{.Management.nais_verification_teams_api_key}}"'
  image.pullPolicy:
    config:
      type: string
  image.repository:
    config:
      type: string
  image.tag:
    config:
      type: string
  slackChannel:
    description: 'The name of the nais<->tenant coop channel (default #nais)'
    config:
      type: string
