# Default values for nais-verification.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/nais-verification
  tag: latest
  pullPolicy: IfNotPresent

secretName: nais-verification-deploy-key
slackChannel: "#nais"

naisTeams:
  apiUrl: http://nais-api/graphql
  apiToken: "" # Mapped in fasit
