name: Build and Deploy
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  build:
    uses: nais/actions/.github/workflows/mise-build-deploy-fasit.yaml@7fb66e62631858376c97cb0b58cb04d06b81743c
    with:
      builds-chart: true
      builds-docker: true
      deploys-to-fasit: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      mise-tasks: '["lint", "fmt-check"]'
      targets: |
        [
          { "target": { "kind": "management", "tenant": "ci-nais" }, "wait": true },
          { "target": { "kind": "management" } }
        ]
    secrets:
      NAIS_IO_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
