name: Build and Deploy
on:
  push:
    branches: [master]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: nais/actions/.github/workflows/mise-build-deploy-fasit.yaml@main
    with:
      builds-chart: true
      deploys-to-fasit: true
      mise-tasks: '["lint", "test"]'
    secrets:
      NAIS_IO_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
